name: prod-PR

on:
  pull_request:
    branches:
      - master

jobs:
  staging-healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Healthcheck the staging endpoint
        run: curl https://app.terraform.io/app/Mutlu/workspaces/Hands-on-with-Terraform-Cloud1/runs/run-WFURGk5evpCns1KZ
